force-app/main/default/objects/Integration_Log__c/Integration_Log__c.object-meta.xml
<CustomObject>
    <description>A custom table to record all integration payload to and from from Salesforce and external systems for auditing and troubleshooting purpose.</description>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>Int-Log-{00000}</displayFormat>
        <label>Integration Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Log__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <description>Endpoint for external system</description>
    <inlineHelpText>Endpoint for external system</inlineHelpText>
    <label>Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Headers__c.field-meta.xml
<CustomField>
    <fullName>Headers__c</fullName>
    <description>Request Headers in JSON Format</description>
    <inlineHelpText>Request Headers in JSON Format</inlineHelpText>
    <label>Headers</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/IsError__c.field-meta.xml
<CustomField>
    <fullName>IsError__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag for any automation provision - In Default it will set to true if Response Code is not 200</description>
    <inlineHelpText>Flag for any automation provision - In Default it will set to true if Response Code is not 200</inlineHelpText>
    <label>Is Error</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <description>Request Method</description>
    <inlineHelpText>Request Method</inlineHelpText>
    <label>Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Request_Body__c.field-meta.xml
<CustomField>
    <fullName>Request_Body__c</fullName>
    <description>Request Body for callout</description>
    <inlineHelpText>Request Body for callout</inlineHelpText>
    <label>Request Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Response_Body__c.field-meta.xml
<CustomField>
    <fullName>Response_Body__c</fullName>
    <description>Actual Response Body recieved from external system</description>
    <inlineHelpText>Actual Response Body recieved from external system</inlineHelpText>
    <label>Response Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Status_Code__c.field-meta.xml
<CustomField>
    <fullName>Status_Code__c</fullName>
    <description>Response Status Code</description>
    <inlineHelpText>Response Status Code</inlineHelpText>
    <label>Status Code</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Status_Message__c.field-meta.xml
<CustomField>
    <fullName>Status_Message__c</fullName>
    <description>Status Message received from External System</description>
    <inlineHelpText>Status Message received from External System</inlineHelpText>
    <label>Status Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Settings__mdt/Integration_Settings__mdt.object-meta.xml
<CustomObject>
    <description>General Integration External Configurable Settings options</description>
    <label>Integration Settings</label>
    <pluralLabel>Integration Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Integration_Settings__mdt/fields/Generate_Log__c.field-meta.xml
<CustomField>
    <fullName>Generate_Log__c</fullName>
    <defaultValue>false</defaultValue>
    <description>External Switch to Turn ON/OFF logging of Integration payload at Log Object (Recommended to TURN ON at Production)</description>
    <label>Generate Log</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/IntegrationLogGenerator.cls
/**********************************************************************************************************************
* @Author:      Tirthankar (Capgemini COE)  
* @Date:        25/05/2020
* @Description: creates integration log records for each callout. part of integration framework.
***********************************************************************************************************************/
public without sharing class IntegrationLogGenerator {

    private static List<Integration_Log__c> integrationLogList = new List<Integration_Log__c>();
    public static boolean invokedFromFuture = false;
    private static Integration_Settings__mdt integrationSettings;
    //This Switch requires if multiple chain callout is being made in a single transaction.
    //Integration Log MUST be inserted after all the callout made to avoid DML exception.
    public static boolean onlyAddToList = false;

    /*******************************************************************************************************************
    * @Author:      Tirthankar (Capgemini COE)  
    * @Date:        25/05/2020
    * @Description: Method for populating integrationSettings
    ********************************************************************************************************************/
    private static void populateSettings(){
        //Populate Integration Settings option from custom meta data
        if(integrationSettings == null){            
            List<Integration_Settings__mdt> integrationSettingsList = [SELECT 
                                                                        Generate_Log__c
                                                                        FROM Integration_Settings__mdt];
            if(integrationSettingsList.size() > 0){
                integrationSettings = integrationSettingsList[0];
            }
        }
    }
    
    /*******************************************************************************************************************
    * @Author:      Tirthankar (Capgemini COE)  
    * @Date:        25/05/2020
    * @Description: creates integration log records for each callout
    * @Revision(s): [Date] - [Change Reference] - [Changed By] - [Description]   
    ********************************************************************************************************************/
    public static void generateIntegrationLog(String endpoint, String method, Map<String, String> headerParamsMap, String requestBody, Integer responseStatusCode, String responseStatus, String responseBody) {
        populateSettings();   
        if(!onlyAddToList){
            if((integrationSettings != null) && integrationSettings.Generate_Log__c){
                if(invokedFromFuture){
                    insertIntegrationLogRecord(endpoint, method, headerParamsMap, requestBody, responseStatusCode, responseStatus, responseBody);
                }else{
                    insertIntegrationLogRecordAsync(endpoint, method, headerParamsMap, requestBody, responseStatusCode, responseStatus, responseBody);
                }    
            }else{
                system.debug('Integration LOG --- '+ endpoint + ' : ' + method + ' : ' + requestBody + ' : ' + responseBody);
            }
        }
        else{
            pushIntegrationLogToList(endpoint, method, headerParamsMap, requestBody, responseStatusCode, responseStatus, responseBody);
        }
    }

    /************************************************************************************************************************************
    * @Author:      Tirthankar Dastidar  
    * @Date:        25/05/2020
    * @Description: this method logs the integration to a separate object in asynchronous way
    ************************************************************************************************************************************/
	@future
	private static void insertIntegrationLogRecordAsync(String endpoint, String method, Map<String, String> headerParamsMap, String requestBody, Integer responseStatusCode, String responseStatus, String responseBody){
        insertIntegrationLogRecord(endpoint, method, headerParamsMap, requestBody, responseStatusCode, responseStatus, responseBody);
	}

    /************************************************************************************************************************************
    * @Author:      Tirthankar Dastidar  
    * @Date:        25/05/2020
    * @Description: this method logs the integration to a separate object in synchronous way
    ************************************************************************************************************************************/
    private static void insertIntegrationLogRecord(String endpoint, String method, Map<String, String> headerParamsMap, String requestBody, Integer responseStatusCode, String responseStatus, String responseBody){
		try{
            pushIntegrationLogToList(endpoint, method, headerParamsMap, requestBody, responseStatusCode, responseStatus, responseBody);
            insertIntegrationLog();
		} catch(Exception e){
			system.debug('IntegrationLogGenerator - insertIntegrationLogRecord - ' + e.getMessage());
		}
    }
    
    /*******************************************************************************************************************
    * @Author:      Tirthankar (Capgemini COE)  
    * @Date:        25/05/2020
    * @Description: push variables into integration log list 
    ********************************************************************************************************************/
    private static void pushIntegrationLogToList(String endpoint, String method, Map<String, String> headerParamsMap, String requestBody, Integer responseStatusCode, String responseStatus, String responseBody){
        Integration_Log__c intLog = new Integration_Log__c();
        intLog.Endpoint__c = endpoint;
        intLog.Method__c = method;
        intLog.Headers__c = JSON.serialize(headerParamsMap);
        intLog.Request_Body__c = requestBody;   
        intLog.Status_Code__c = responseStatusCode;
        intLog.Status_Message__c = responseStatus;
        intLog.Response_Body__c = responseBody;
        if(responseStatusCode != 200){
            intLog.IsError__c = true;
        }
        integrationLogList.add(intLog);
    }   
    
    /************************************************************************************************************************************
    * @Author:      Tirthankar (Capgemini COE)  
    * @Date:        10/02/2019
    * @Description: invoke this method directly to insert pending integration logs (applicable wen async insert is not feasible)
    ************************************************************************************************************************************/
	public static void insertIntegrationLog(){
        if(!integrationLogList.isEmpty()){
            insert integrationLogList;
            integrationLogList.clear();
        } 
    }    
}